### PR TITLE
planner service API changes & fixes, HalfFitPod planner tests

### LINKED ISSUE #84: [Feature] Simulator executing Multi-Simulation-Per-Group Strategy that leverages Node Scoring
**How to categorize this issue?**

/area auto-scaling
/kind enhancement

**What would you like to be added**:

- This simulator is used for the simulation strategy named `SimulationStrategyMultiSimulationsPerGroup=multi-simulations-per-group`), implements and implements `ScaleOutSimulator.Simulate(ctx context.Context, resultCh chan<- ScalingPlanResult)`
- We create `SimGroupKey`for all `NodePool` and `NodeTemplate` priority combinations.
- We first create simulations where when each simulation is operated against a simulation view comprising of existing nodes and existing pods and unscheduled pods. When the simulation is run, it creates a simulated scaled node that is generated from a combination of Node Pool, Node Template and Availability Zone and then executes the scheduler to assign unscheduled pods to simulated scaled node or existing node.
- We order the simulation groups according to Node Pool Priority and Node Template Priority. (lower value is higher priority)
- We iterate through each SimulationGroup and concurrently run Simulation's within that group.
- After the Simulation is executed, the Node-Pod assignments (if any) are done. Each simulation is then scored using the node scorer. A winner simulation is picked.
- As long there is a winner and there are leftover unscheduled pods, we continue running simulation in the same group by updating the view with the view state of the previous winning simulation.
- If there is no winner and there are leftover unscheduled pods, then we move to the next `SimulationGroup`
    - If there are no leftover unscheduled pods, then we exit looping.
- Once we have all the winner node scores (`service.NodeScore`), we produce the `service.ScalingPlanResult` and emit then on results channel
- The simulator honors the provided Context when performing simulations

### LINKED ISSUE #88: Simple One-Pool Scale-Out Scenarios
**What would you like to be added**:

Basic Scale Out Scenarios are the *dead-simplest* scaling scenarios restricted to just a SINGLE type of `NodePool` and do not involve more than a single kind of Pod assignable to nodes of that particular `NodePool`.  (ie only 1 variants of resource request per `NodePool`) . It should immediately possible for human to judge whether scale-out plan produced is optimal by mark-1 eyeball.

- [x] Scale Out Scenario for Cluster Constraints Involving just ONE `NodePool` and One `instanceType` .  
- [x] Basic Cluster Snapshot Variants
       - Contains zero or more existing Nodes belonging to this `NodePool`
       - Zero or more existing assigned Pods and one or more unscheduled Pods.

### LINKED ISSUE #91: Two Pool Scale-Out Scenarios with Basic Variants
**What would you like to be added**:

Basic Two-Pool Scale Out Scenarios are restricted to 2 `NodePool`'s with 1 `NodeTemplate` each and limited to Pod variants that either nearly fit or half-fit the pool's `NodeTemplate`.  It should still be possible for a human with minimal effort to judge whether scale-out plans are optimal by mark-1 eyeball.

Two Pool Basic Scale Out scenarios DO NOT consider Pool Affinity, TSC or Backoff for simplicity reasons.

- [x] Scale Out Tests for Cluster Constraints Involving just `2` NodePool `p` and`q`, each with a different `NodeTemplate` associated with a progressively larger `instanceType(s)`.
- [x] Scale Out Tests for Cluster Constraints Involving just `2` NodePool's `p` and `q`, `large` each with a different `NodeTemplate` named `normal` associated with a progressively larger `instanceType(s)`.

### PR DESCRIPTION
**Pull request by elankath**
AggregatedRequests now ResourceList, HalfFitPod planner tests

* introduced planner basic one-pool half-fit pod scale-out tests
* deleted checked-in cluster snapshots - now generated synthetically
* removed functions which used map[corev1.ResourceName]int64
* use objutil.ScalingAdvisorScheme when runtime.Scheme is needed
* use community accepted json package aliases: stdjson,kjson,utiljson
* Snapshot is not optional in ScalingAdviceRequest and hence should not be a pointer field
* Introduce planner TestArgs and TestData to factor common unit-test setup
* Refactored types and utility functions in samples to use resource.Quantity (hold your nose)
* SimulationStrategy->SimulatorStrategy as it a strategy to choose the simulator implementation
* log count of unscheduled pods and nodes at  verbosity `2`. Log node/podinfo summary at level `4`.
* testutil.NewTestContext to setup logr testing logger and test contexts with verbosity, timeout, signals and cleanup.
* pricing API is now in separate pkg as vedran mentioned
* ScalingPlannerService binary now named `scalp`
* ScalingPlannerService now supports a REST API
* Resettable.Reset now returns an error
* json tags now present on all relevant planner api types
* types.NamespacedName cannot be embedded since it has no json tags. (so silly)
* planner sentinel errors now remove the wording of "advice". Advice is for the operator.
* removed service API as it is merely planner as a launchable Service and does not need separate API package
* Resettable.Reset now returns an error as its delegate calls may cause errors.
* Changed `ScalingAdviceRequest` and `ScalingAdviceResult` to `plannerapi.Request` and `plannerapi.Response` respectively.
* Changed `ScalingPlanner.Plan` signature to `Plan(ctx context.Context, req Request) <-chan Response`
* Changed `ScaleOutSimulator.Simulate` signature to `Simulate(ctx context.Context, request *Request, simulationCreator SimulationCreator) (planResult <-chan ScaleOutPlanResult)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #91
Fixes #88
Fixes #84

**Special notes for your reviewer**:

**Release note**:

```bugfix developer
NONE
```

### CODE REVIEW

File: api/core/v1alpha1/scalingconstraints.go [hunk 1]
```diff
@@ -80,7 +81,7 @@ type NodePool struct {
 	// NodeTemplates is a slice of NodeTemplate.
 	NodeTemplates []NodeTemplate `json:"nodeTemplates"`
 	// Priority is the priority of the node pool.
-	Priority int32 `json:"priority"`
+	Priority int32 `json:"priority,omitzero"`
```
Comment (unmarshall) [inline api/core/v1alpha1/scalingconstraints.go]: `0` default value of int32 is a valid priority. Why should it be omitted?

File: api/core/v1alpha1/scalingconstraints.go [hunk 2]
```diff
@@ -104,9 +105,9 @@ type NodeTemplate struct {
 	// InstanceType is the instance type of the node template.
 	InstanceType string `json:"instanceType"`
 	// Priority is the priority of the node template. The lower the number, the higher the priority.
-	Priority int32 `json:"priority"`
+	Priority int32 `json:"priority,omitzero"`
```
Comment (unmarshall) [inline api/core/v1alpha1/scalingconstraints.go]: 0 default value of int32 is a valid priority. Why should it be omitted?

File: common/objutil/objutil.go [hunk 3]
```diff
@@ -26,15 +27,15 @@ import (
 	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/runtime/schema"
 	"k8s.io/apimachinery/pkg/runtime/serializer"
-	apijson "k8s.io/apimachinery/pkg/runtime/serializer/json"
+	kjson "k8s.io/apimachinery/pkg/runtime/serializer/json"
 	"k8s.io/apimachinery/pkg/types"
-	kjson "k8s.io/apimachinery/pkg/util/json"
+	utiljson "k8s.io/apimachinery/pkg/util/json"
```
Comment (unmarshall) [inline common/objutil/objutil.go]: can we rename the alias to `jsonutil`?

File: minkapi/viewutil/viewutil.go [hunk 4]
```diff
@@ -39,18 +41,27 @@ func LogNodeAndPodNames(ctx context.Context, prefix string, view minkapi.View) e
...
-			"region", node.Labels[corev1.LabelTopologyRegion],
-			"zone", node.Labels[corev1.LabelTopologyZone])
+	log.V(2).Info(prefix+"|count of nodes and pods",
+		"viewName", view.GetName(),
+		"totalNodes", len(allNodes),
+		"totalPods", len(allPods),
+		"totalUnscheduledPods", podutil.CountUnscheduledPods(allPods))
+	if logutil.VerbosityFromContext(ctx) > 2 {
+		for idx, pod := range allPods {
+			log.V(3).Info(prefix+"|pod in view",
```
Comment (unmarshall) [inline minkapi/viewutil/viewutil.go]: Make this level 5 as it will result in truck load of logs for level 3.

File: planner/planner_test.go [hunk 5]
```diff
@@ -19,196 +20,171 @@ import (
...
+	PoolCategory                      samples.PoolCategory
+	SimulatorStrategy                 commontypes.SimulatorStrategy
+	NodeScoringStrategy               commontypes.NodeScoringStrategy
+	AdviceGenerationMode              commontypes.ScalingAdviceGenerationMode
+	Timeout                           time.Duration
+}
+
+// TestData holds all the common test data necessary for carrying out the scale-out unit-tests of the ScalingPlanner and asserting conditions
+type TestData struct {
+	Planner        plannerapi.ScalingPlanner
```
Comment (unmarshall) [inline planner/planner_test.go]: `ScalingPlanner` cannot be categorized as `TestData`.

File: api/core/v1alpha1/scalingconstraints.go [hunk 6]
```diff
@@ -104,9 +105,9 @@ type NodeTemplate struct {
...
 	// MaxVolumes is the max number of volumes that can be attached to a node of this instance type.
-	MaxVolumes int32 `json:"maxVolumes"`
+	MaxVolumes int32 `json:"maxVolumes,omitzero"`
```
[the remark this answers is not in the document]
Comment (elankath) [reply api/core/v1alpha1/scalingconstraints.go]: Right now, we don't use it but it cannot be zero. Again, please don't confuse serialization with vaidation. Presence or absence of `omitzero` is irrelevant here except to save space.

File: minkapi/viewutil/viewutil.go [hunk 7]
```diff
@@ -39,18 +41,27 @@ func LogNodeAndPodNames(ctx context.Context, prefix string, view minkapi.View) e
...
+				"viewName", view.GetName(), "idx", idx, "podName", pod.Name, "podNamespace", pod.Namespace,
+				"assignedNodeName", pod.Spec.NodeName, "podRequests", pod.Spec.Containers[0].Resources.Requests)
+		}
+		for _, node := range allNodes {
+			log.V(3).Info(prefix+"|node in view",
```
[the remark this answers is not in the document]
Comment (elankath) [reply minkapi/viewutil/viewutil.go]: Made it 4 now. 5 is for very-very low level stuff.

**Review by unmarshall — APPROVED** [review]
